# Review Text Analysis

In [27]:
import numpy as np

a = np.zeros(8)
print(a)
print(type(a))

b = np.ones((2,8))
print(b)
print(type(b))

c = np.arange(3,10)
print(c)
print(type(c))

d = np.empty(10)
print(d)
print(type(d))


[0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
[3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[2.41907520e-312 2.33419537e-312 8.48798317e-313 2.37663529e-312
 2.35541533e-312 2.14321575e-312 8.48798317e-313 8.70018275e-313
 1.18831764e-312 8.70018274e-313]
<class 'numpy.ndarray'>
